language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7

script:
  - ./bin/phpunit --configuration tests/phpunit.xml.dist
  - ./bin/sabre-cs-fixer fix lib/ --dry-run --diff

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - composer install
