language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7

matrix:
  fast_finish: true
  allow_failures:
    - php: 7

script:
  - ./bin/phpunit --configuration tests/phpunit.xml.dist
  - ./bin/phpcs  -p --standard=tests/phpcs/ruleset.xml lib/

before_script: composer install --dev
